import {Injectable} from '@angular/core';
import {FirestoreService} from "../../data/http/firestore.service";
import {BatchDocuments} from "./BatchInterface";

@Injectable({
  providedIn: 'root'
})
export class BatchService {
  constructor(private firestoreService: FirestoreService) {
  }

  createBatch(documents: BatchDocuments[]): Promise<void> {
    const batch = this.firestoreService.getDbRef().batch();
    documents.forEach(doc => {
      const docRef = this.firestoreService.getDocumentRefByAutogeneratedId(doc.collection, doc.docId);
      if (doc.action === 'delete') {
        // @ts-ignore
        batch[doc.action](docRef);
      } else {
        // @ts-ignore
        batch[doc.action](docRef, doc.payload);
      }
    });
    return batch.commit();
  }

  getMapper(collection: string, docId: string, payload: any, action: any) {
    return {
      collection,
      docId,
      payload,
      action
    }
  }
}
